In [3]:
class person():
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
## Derived CLass 
class Employee(person):
    def isEmployee(self):
        return True
emp = person("Anil")
emp2=Employee("Mahesh")
emp1 = person("Vamsi ")
print(emp.getName(),emp.isEmployee())
print(emp1.getName(),emp1.isEmployee())
emp = person("Akhil")
print(emp.getName(),emp.isEmployee())
print(emp2.getName(),emp2.isEmployee())



Anil False
Vamsi  False
Akhil False
Mahesh True


In [1]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(lst)



[1, 2, 3, 4]


In [2]:
lst= [1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)


(4,)
int32


In [3]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
a1= np.array([1,2,3])
a2= np.array([4,5,6])
print(np.hstack((a1,a2)))


[1 2 3 4 5 6]


In [1]:
class test:def __init__(self,a)
    self.a=self
    def display(self):
        print(self.a)
    obj=test()
    obj=displat()

SyntaxError: invalid syntax (<ipython-input-1-34442c70833a>, line 1)